version: '3.8'

services:
  redis-6380:
    image: redis:6-alpine
    container_name: redis-6380
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "6380:6380"
      - "16380:16380"

    volumes:
      - ./redis-6380/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-6380/data:/data
    command: 
      - "redis-server" 
      - "/usr/local/etc/redis/redis.conf"
    networks:
      - redis-cluster
      
  redis-6381:
    image: redis:6-alpine
    container_name: redis-6381
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "6381:6381"
      - "16381:16381"
    volumes:
      - ./redis-6381/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-6381/data:/data
    command:
      - "redis-server" 
      - "/usr/local/etc/redis/redis.conf"
    networks:
      - redis-cluster
      
  redis-6382:
    image: redis:6-alpine
    container_name: redis-6382
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "6382:6382"
      - "16382:16382"
    volumes:
      - ./redis-6382/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-6382/data:/data
    command:
      - "redis-server" 
      - "/usr/local/etc/redis/redis.conf"
    networks:
      - redis-cluster
  
  redis-6383:
    image: redis:6-alpine
    container_name: redis-6383
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "6383:6383"
      - "16383:16383"
    volumes:
      - ./redis-6383/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-6383/data:/data
    command:
      - "redis-server" 
      - "/usr/local/etc/redis/redis.conf"
    networks:
      - redis-cluster         
                        
  redis-6384:
    image: redis:6-alpine
    container_name: redis-6384
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "6384:6384"
      - "16384:16384"
    volumes:
      - ./redis-6384/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-6384/data:/data
    command:
      - "redis-server" 
      - "/usr/local/etc/redis/redis.conf"
    networks:
      - redis-cluster
      
  redis-6385:
    image: redis:6-alpine
    container_name: redis-6385
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "6385:6385"
      - "16385:16385"
    volumes:
      - ./redis-6385/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-6385/data:/data
    command:
      - "redis-server" 
      - "/usr/local/etc/redis/redis.conf"
    networks:
      - redis-cluster

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: always
    ports:
      - '8080:8080'
      - '6379:6379'
    depends_on:
      - redis-6380
      - redis-6381
      - redis-6382
      - redis-6383
      - redis-6384
      - redis-6385
    networks:
      - redis-cluster
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
                                                      
networks:
  redis-cluster:
    driver: bridge
